<div class="nav navbar align-items-center justify-content-between bg-dark" style="height:4rem">
    <h4 class="m-0 text-light">Editar registro de entrada</h4>
    <h4 class="m-0 text-white"><i class="fas fa-walking mr-2" style="font-size:28px"></i></h4>
</div>
<div class="d-flex align-items-center justify-content-center px-1" style="min-height: 91vh">
    <div class="py-4 px-3 card" style="width:30rem">
        <form action="/update_visitor_entry" method="post">
            <input type="hidden" name="id_visitante" value="<?=$_POST['id_visitante']?>">  
            <abbr title="Essa informação só pode ser editada na tabela de cadastros">
                <div class="label-float mt-4">    
                    <input class="form-custom form-control mt-1" size="60" placeholder="Nome" value="<?=$_POST['nome']?>" disabled>
                    <label>Nome</label>
                </div>
            </abbr>
            <?php if(strlen($_POST['cpf_rg']) == 14 && $_POST['uf'] == '--'){?>
                <abbr title="Essa informação só pode ser editada na tabela de cadastros">
                    <div class="label-float mt-4">
                        <input class="form-custom form-control mt-2" size="60" placeholder="CPF" value="<?=$_POST['cpf_rg']?>" disabled>
                        <label>CPF</label>
                    </div>
                </abbr>
            <?php } else {?>
                <abbr title="Essa informação só pode ser editada na tabela de cadastros">
                    <label class="mt-4 mb-0 text-secondary">UF</label>
                    <select class="form-custom form-control m-0 p-0" style="border-bottom: 2px solid #20B2AA!important;" disabled>
                        <option value="<?=$_POST['uf']?>"><?=$_POST['uf']?></option>
                    </select>
                </abbr>
                <abbr title="Essa informação só pode ser editada na tabela de cadastros">
                    <div class="label-float mt-4" id="input-rg-registro">
                        <input class="form-custom form-control mt-2" size="60" placeholder="RG" value="<?=$_POST['cpf_rg']?>" disabled>
                        <label>RG</label>
                    </div>
                </abbr>
            <?php }?>
            <div class="label-float mt-4">    
                <input type="text" name="apartamento" class="form-custom form-control mt-2" size="60" maxlength="5" placeholder="Apartamento" value="<?=$_POST['apartamento']?>" required>
                <label>Apartamento</label>
            </div>
            <div class="label-float mt-4">    
                <input type="text" name="bloco" class="form-custom form-control mt-2" size="60" maxlength="1" placeholder="Bloco" value="<?=$_POST['bloco']?>" required>
                <label>Bloco</label>
            </div>
            <button type="submit" class="btn btn-register text-white w-100 mt-5">Atualizar</button>   
            <a href="/visitors" class="btn btn-danger text-white w-100 mt-2">Voltar</a>      
        </form>
    </div>
</div>
